services:
  - type: web
    name: my-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi"
    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        value: "django-insecure-7m4q*je8e$*kp0@wkwpk=v-k4^p#ww#7gu%+1=v0y418i$6)*4"
      - key: ALLOWED_HOSTS
        value: "twojadomena.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
databases:
  - name: my-database
    databaseName: mydbname
    user: myuser
