# Generated by Django 5.2.3 on 2025-06-20 07:18

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("submitted", "Submitted")],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.submission_upload_path
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="core.teacherprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.group",
            ),
        ),
    ]
