# Generated by Django 5.2.3 on 2025-06-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_submission_status_submission_submitted_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="ClassGroup",
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacherprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
