# Generated by Django 5.2.3 on 2025-06-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_group_classgroup_alter_teacherprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
